### PR TITLE
Only apply imagePullPolicy to plugins if instructed

### LINKED ISSUE #1652: Customizing Plug-in PodSpecs not applying imagePullPolicy
Customizing Plug-in PodSpecs not applying imagePullPolicy

**What steps did you take and what happened:**

Using this pod spec `e2e.yaml`: 
```
podSpec:
  containers: []
  imagePullPolicy: Always
  restartPolicy: Never
  imagePullSecrets:
  - name: regcred
  serviceAccountName: sonobuoy-serviceaccount
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
  - key: kubernetes.io/e2e-evict-taint-key
    operator: Exists
sonobuoy-config:
  driver: Job
  plugin-name: e2e
  result-format: manual
  result-files:
    - e2e-results.yaml
spec:
  args:
  - ./run-e2e.sh
  command:
  - ./run.sh
  image: some/private/registry/e2e:latest
  imagePullPolicy: Always
  name: plugin
  resources: {}
  volumeMounts:
  - mountPath: /tmp/results
    name: results
```
And this command : 

```
sonobuoy run  --namespace e2e --plugin //tmp/e2e-d25o/e2e.yaml  --plugin-env e2e.E2E_FOCUS="test" --skip-preflight --wait
```

`sonobuoy-e2e-job-f072ea79e49c443a` pod running with `imagePullPolicy: IfNotPresent`

**What did you expect to happen:**

`sonobuoy-e2e-job-f072ea79e49c443a` pod running with `imagePullPolicy: Always`
    

**Anything else you would like to add:**

The expected behavior is working on the release https://github.com/vmware-tanzu/sonobuoy/releases/tag/v0.50.0
Not working on v0.55.0 and v0.56.3

**Environment:**

- Sonobuoy version:
```
Sonobuoy Version: v0.56.3
MinimumKubeVersion: 1.17.0
MaximumKubeVersion: 1.99.99
GitSHA: 1005bee8fff1b8daa30ddbcca717d03384630a71
GoVersion: go1.16.14
Platform: linux/386
API Version check skipped due to missing `--kubeconfig` or other error
 ```
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by johnSchnake**
Adds a new option which allows the user to specify whether or
not to apply the imagePullPolicy to all plugins and override
their stated values.

This is important since even the default value was overwriting
explicit values in the plugins leading to confusing behavior.

Techinically a breaking change for someone who was running
sonobuoy CLI with the --image-pull-policy flag to overwrite explicit
values. They will now need to add the --force-image-pull-policy flag
to obtain the same behavior. This makes all modifications to plugins
explicit via some option rather than this one being implicit.

Fixes #1652

Signed-off-by: John Schnake <jschnake@vmware.com>

**Release note**:
```
Users will now need to add the --force-image-pull-policy flag if they want the plugins to use the same imagePullPolicy as the Sonobuoy aggregator/worker containers.  Sonobuoy will respect the imagePullPolicy stated in the plugin definitions otherwise.
```

### CODE REVIEW

**Comment by johnSchnake** [comment]
Not a big change but just lots of golden files being tweaked.

Added a field to the config object and plumbed it through to a flag. Gated logic on that value.

File: pkg/client/gen_test.go [hunk 1]
```diff
@@ -460,7 +463,7 @@ func TestGenerateManifestGolden(t *testing.T) {
 					},
 				},
 			},
-			goldenFile: filepath.Join("testdata", "imagePullPolicy-all-plugins.golden"),
+			goldenFile: filepath.Join("testdata", "imagePullPolicy-not-all-plugins.golden"),
```
Comment (johnSchnake) [inline pkg/client/gen_test.go:466]: This was actually a previously duplicated test oddly. Now one is for forcing the values, and the other isnt.

File: test/integration/testdata/gen-imagePullPolicy.golden [hunk 2]
```diff
@@ -0,0 +1,169 @@
...
+      - name: SONOBUOY_CONFIG_DIR
+        value: /tmp/sonobuoy/config
+      - name: SONOBUOY_K8S_VERSION
+        value: ignore
+      - name: SONOBUOY_PROGRESS_PORT
+        value: "8099"
+      - name: SONOBUOY_RESULTS_DIR
+        value: /tmp/sonobuoy/results
+      image: hello:v9
+      imagePullPolicy: Always
```
Comment (johnSchnake) [inline test/integration/testdata/gen-imagePullPolicy.golden:87]: Not forced and has its value, not the default (IfNotPresent)
