### PR TITLE
Fix typo causing e2e-repo-config to set env var to wrong value

### LINKED ISSUE #1375: broken e2e repolists
https://github.com/vmware-tanzu/sonobuoy/commit/c5063fb423ae3c0bcf68d2bf14b414f8b10c4988#r54347296

**Environment:**

- Sonobuoy version: v0.53
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below)

### PR DESCRIPTION
**Pull request by johnSchnake**
Previously used configs instead of config in path. Fixed typo
and added a test for this. However, it really only shows the env
var since the mount doesn't get created until the aggregator actually
creates the plugin pods.

Fixes #1375

Signed-off-by: John Schnake <jschnake@vmware.com>

**Release note**:
```
Fixes a typo which caused e2e-repo-config to set the env var incorrectly
```

### CODE REVIEW

File: cmd/sonobuoy/app/args.go [hunk 1]
```diff
@@ -506,7 +506,7 @@ func (f *e2eRepoFlag) Set(str string) error {
 		}
 		m.Spec.Env = append(m.Spec.Env, corev1.EnvVar{
 			Name:  "KUBE_TEST_REPO_LIST",
-			Value: fmt.Sprintf("/tmp/sonobuoy/configs/%v", name),
+			Value: fmt.Sprintf("/tmp/sonobuoy/config/%v", name),
```
Comment (johnSchnake) [inline cmd/sonobuoy/app/args.go:509]: This is the one fix

File: test/integration/sonobuoy_integration_test.go [hunk 2]
```diff
@@ -517,6 +517,10 @@ func TestExactOutput_LocalGolden(t *testing.T) {
 			desc:       "gen respects kube-conformance-image for both plugin and config issue 1376",
 			cmdLine:    "gen --kube-conformance-image=custom-image --kubernetes-version=v9.8.7",
 			expectFile: "testdata/gen-issue-1376.golden",
+		}, {
```
Comment (johnSchnake) [inline test/integration/sonobuoy_integration_test.go:520]: This is the new test case

File: test/integration/testdata/gen-issue-1375.golden [hunk 3]
```diff
@@ -0,0 +1,228 @@
...
+      - name: E2E_FOCUS
+        value: \[Conformance\]
+      - name: E2E_PARALLEL
+        value: "false"
+      - name: E2E_SKIP
+        value: \[Disruptive\]|NoExecuteTaintManager
+      - name: E2E_USE_GO_RUNNER
+        value: "true"
+      - name: KUBE_TEST_REPO_LIST
+        value: /tmp/sonobuoy/config/tiny-configmap.yaml
```
Comment (johnSchnake) [inline test/integration/testdata/gen-issue-1375.golden:107]: Evidence of the fix

**Comment by johnSchnake** [comment]
Set up a cluster and confirmed this worked to resolve the issue; I just didnt want to merge it and see that it we had another typo too. Seems this fixes it.
