### PR TITLE
Results aggregation should consider the errors directory

### LINKED ISSUE #897: Result aggregation doesn't take into account the /errors directory
**What steps did you take and what happened:**
If you do something like
```
sonobuoy run --timeout=10 --plugin do-nothing-plugin --wait
sonobuoy status --json
```

You'll see that the plugin gets reported as unknown because it didnt have any results. The issue is that the result post-processing looks in the results directory for actual results but doesn't look into the `errors` directory to process the Sonobuoy reported issues like timeouts or failure to start a plugin.

**What did you expect to happen:**
If Sonobuoy is reporting an error and saving it into the tarball, our own post-processing should pick up on that and mark the plugin status as `failed` or `errored` with the details copied from the `errors.json` file.

**Anything else you would like to add:**
Currently, the e2e plugin, when timing out, is told to stop and so it still reports results (even if they are partial results). This is changing as part of #883 though.

### PR DESCRIPTION
**Pull request by johnSchnake**
**What this PR does / why we need it**:
Whenever the aggregator itself deems that a plugin has failed,
(e.g. pods didnt start, timeouts, etc) then it writes its results
into an errors directory. This should be considered when doing
results aggregation so that they can be resulted as failures.

Otherwise, the plugin is just reported as having 0 results and
having an unknown status even though Sonobuoy may have been the one
to mark it as failure internally.

**Which issue(s) this PR fixes**
Related to #883
Fixes #897

**Special notes for your reviewer**:

**Release note**:
```
When inspecting plugin results (for reporting via `sonobuoy status` and `sonobuoy results`) errors saved in the `<plugin>/errors` directory which are reported by Sonobuoy itself are now considered. This should help make certain failure modes such as timeout more clear.
```

### CODE REVIEW

File: pkg/client/results/processing.go [hunk 1]
```diff
@@ -146,48 +148,120 @@ func PostProcessPlugin(p plugin.Interface, dir string) (Item, error) {
 	return i, err
 }
 
+// processNodesWithProcessor is called to invoke processDir on each node-specific directory contained
+// underneath the given dir. The directory is assumed to be either the results directory or errors directory
+// which should have the nodes as subdirectories. It returns an item for each node processed and an error
+// only if it couldn't open the original directory. Any errors while processing a specific node are logged
+// but not returned.
+func processNodesWithProcessor(p plugin.Interface, baseDir, dir string, processor postProcessor, selector fileSelector) ([]Item, error) {
```
Comment (johnSchnake) [inline pkg/client/results/processing.go]: This method is just code moved code, not new code. Extracted from the `processPluginWithProcessor` method.

File: pkg/client/results/processing.go [hunk 2]
```diff
@@ -146,48 +148,120 @@ func PostProcessPlugin(p plugin.Interface, dir string) (Item, error) {
...
 	results := Item{
 		Name: p.GetName(),
 	}
 
 	if isDS {
-		nodeDirs, err := ioutil.ReadDir(pResultsDir)
+		items, err := processNodesWithProcessor(p, baseDir, pResultsDir, processor, selector)
 		if err != nil {
-			return Item{}, err
+			logrus.Warningf("Error processing results entries for plugin %v: %v", p.GetName(), err)
```
Comment (johnSchnake) [inline pkg/client/results/processing.go]: TODO: rather than log here, I want to return a slice of errors and just return them all and log at the parent if we want. Awkward to have lower level methods not pass up their errors.

I really just wanted to continue processing after errors so on my first pass I added logging rather than returning.

File: pkg/client/results/processing.go [hunk 3]
```diff
@@ -146,48 +148,120 @@ func PostProcessPlugin(p plugin.Interface, dir string) (Item, error) {
...
+		return resultObj, errors.Wrapf(err, "opening file %v", currentFile)
+	}
+	defer infile.Close()
+
+	dec := json.NewDecoder(infile)
+	result := map[string]string{}
+	if err := dec.Decode(&result); err != nil {
+		return resultObj, errors.Wrapf(err, "decoding file %v", currentFile)
+	}
+	logrus.Infof("SCHNAKE got errors.json file with %#v", result)
```
Comment (johnSchnake) [inline pkg/client/results/processing.go]: Debug line.

File: pkg/client/results/testdata/mockResults/plugins/ds-errors-02/ds-errors-02.golden.json [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+"details": {
+"data": "foo",
+"error": "testerr"
+}
+}
+]
+},
+{
+"name": "node2",
+"status": "",
```
Comment (johnSchnake) [inline pkg/client/results/testdata/mockResults/plugins/ds-errors-02/ds-errors-02.golden.json]: This shouldn't be empty. #937 had seen this before and understood it to be for unknown nodes but here it is something that has a failed leaf node. Need to identify why this isnt bubbling up.

Comment (johnSchnake) [reply pkg/client/results/testdata/mockResults/plugins/ds-errors-02/ds-errors-02.golden.json]: Found the other bug; it was that `aggregateStatuses` was doing early exit on failures. That would bubble up the right values, but wasn't ensuring that every node was visited. #937 has been updated.

**Comment by johnSchnake** [comment]
Green tests, reasonable coverage. Going to just merge and move forward. Can fixup if desired but this is a blocker for the #883 which is a slightly larger change and I want ready for review soon.
