### PR TITLE
Deterministic TagPair assertion of custom registry

### LINKED ISSUE #1181: Inconsistent unit test result
**What steps did you take and what happened:**
Unit tests under `pkg/image` deliver inconsistent result

**What did you expect to happen:**
Unit tests should be consistent

**Anything else you would like to add:**
My initial reaction is probably improper mock or race conditions. This occurred on CircleCI on `2b8d1eabc96070954a3fad5c482973fffefd2506` as part of #1179.

[Failed on first run](https://app.circleci.com/pipelines/github/vmware-tanzu/sonobuoy/456/workflows/fa9eda7e-f881-4320-b79d-309c5698ebfc/jobs/2075), but without anything being changed, [it passed on second run](https://app.circleci.com/pipelines/github/vmware-tanzu/sonobuoy/456/workflows/29a446f3-ca53-410c-b0b7-22235be6bd7e/jobs/2081).

image

### PR DESCRIPTION
**Pull request by wilsonehusin**
This ensures that we are testing images which were overriden by custom
registry. Some registries are meant to be excluded from override.

See #1181 for details.

Signed-off-by: Wilson E. Husin <whusin@vmware.com>

**What this PR does / why we need it**:
Stabilizes unit tests flake

**Which issue(s) this PR fixes**
- Fixes #1181

**Special notes for your reviewer**:
-

**Release note**:
```
NONE
```

### CODE REVIEW

File: pkg/image/manifest_test.go [hunk 1]
```diff
@@ -164,21 +164,28 @@ func TestGetE2EImageTagPairs(t *testing.T) {
...
 	}
 
-	// Check one of the returned image pairs to ensure correct format
-	imageTagPair := imageTagPairs[0]
-	if strings.HasPrefix(imageTagPair.Src, customRegistry) {
-		t.Errorf("Src image should not have custom registry prefix: %q", imageTagPair.Src)
+	// As a sample, check one of the images for E2E and assert their mapping
+	var e2eImageTagPair TagPair
+	for _, imageTagPair := range imageTagPairs {
+		if strings.Contains(imageTagPair.Src, "e2e") {
```
Comment (vladimirvivien) [inline pkg/image/manifest_test.go:173]: So this ensures the name of the image:tag contains `e2e` in the string ?  Is that always the case ?

File: pkg/image/manifest_test.go [hunk 2]
```diff
@@ -164,21 +164,28 @@ func TestGetE2EImageTagPairs(t *testing.T) {
...
+			e2eImageTagPair = imageTagPair
+			break
+		}
+	}
+
+	if strings.HasPrefix(e2eImageTagPair.Src, customRegistry) {
```
Comment (vladimirvivien) [inline pkg/image/manifest_test.go:179]: Also, if that loop never break (above) does that create any initializiation hazard for var `e2eImageTagPair`? It does not seem like it (since e2eimagetagpair is a struct) but check please.

**Review by vladimirvivien — COMMENTED** [review]
I will admit, that part of the code is murky to me.  But, left some comments anyway.

File: pkg/image/manifest_test.go (hunk 1 above)
Comment (wilsonehusin) [reply pkg/image/manifest_test.go:173]: this ensures that what we validate is only the `e2e` in string, which should scope to `gcr.io/kubernetes-e2e-test-images` or `k8s.gcr.io/e2e-test-images` -- both are overridable with custom registry

File: pkg/image/manifest_test.go (hunk 2 above)
Comment (wilsonehusin) [reply pkg/image/manifest_test.go:179]: ah yeah that's a good point. I think `e2e` will always exist, but I also think it's valuable to have check to assert it.

**Review by vladimirvivien — APPROVED** [review]
LGTM
