### PR TITLE
Fix bug where 'retrieve' fails if filepath diectories DNE

### LINKED ISSUE #1689: Sonoboy retrieve fails saving on a different path
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Running sonobuoy retrieve fails if the path specified using -f contains a path to a directory.

```
$ sonobuoy retrieve -f /tmp/work/results.tar.gz
error retrieving results: non-zero data ¸ (byte 184) read after tar EOF
$ sonobuoy retrieve 
202205050313_sonobuoy_9e1c1194-9068-4899-b8b2-000c8bb19fd1.tar.gz
$ sonobuoy retrieve -f /tmp/work/results.tar
error retrieving results: non-zero data ¸ (byte 184) read after tar EOF
$ sonobuoy retrieve -f results.tar
results.tar
```

**What did you expect to happen:**
Able to save the results tar ball on a directory different to where the  sonobouy binary  is located

**Environment:**

- Sonobuoy version: v0.56.4

### PR DESCRIPTION
**Pull request by johnSchnake**
The logic takes a path and a file; if the file has path values in it
that do not exist, then os.Create was failing but the MkdirAll logic
wasn't looking for paths in that.

To fix this, I just reconcile the directory/filename to get the full path
and process it accordingly sooner.

Fixes #1689

**Special notes for your reviewer**:
No tests really hit this but its a pretty trivial change. Just going forward with it having been tested manually. In my opinion this isn't worth a big test setup to check at this time.

**Release note**:
```
Fixed a bug where `sonobuoy retrieve -f <filename>` fails if the filename contains path elements that do not exist. 
```

### CODE REVIEW

File: pkg/client/retrieve.go [hunk 1]
```diff
@@ -130,17 +134,15 @@ func UntarAll(reader io.Reader, destDir, filename string) (filenames []string, r
...
-		if err != nil {
-			returnErr = errors.Wrap(err, "failed to drain the tar reader")
+		err := drainReader(reader)
+		switch {
+		case err == nil:
+			return
+		case returnErr == nil && err != nil:
+			returnErr = err
+		case returnErr != nil && err != nil:
+			logrus.Warnf("Error while draining reader (%v) but there was a previous error that may be the root cause: %v", err, returnErr)
```
Comment (johnSchnake) [inline pkg/client/retrieve.go:144]: This section was just refactored for clarity when hitting both errors. Found when debugging the original issue so I included it here.
